# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"pgn2df": "01_pgn2csv.ipynb",
         "pgn2csv": "01_pgn2csv.ipynb",
         "evaluate_game": "02_engine_analysis.ipynb",
         "evaluate_pgn": "02_engine_analysis.ipynb"}

modules = ["etf.py",
           "engine.py"]

doc_url = "https://NateSolon.github.io/chessdata/"

git_url = "https://github.com/NateSolon/chessdata/tree/main/"

def custom_doc_links(name): return None
