# AUTOGENERATED! DO NOT EDIT! File to edit: 01_pgn2csv.ipynb (unless otherwise specified).

__all__ = ['pgn2df']

# Cell
import chess.pgn
import pandas as pd

# Cell
def pgn2df(pgn):
    game = chess.pgn.read_game(pgn)
    game_info = []
    while game:
        game_info.append(dict(game.headers))
        game = chess.pgn.read_game(pgn)
    df = pd.DataFrame(game_info)
    return df